

import 'package:test/util/app_strings.dart';

const Map<LabelsText, String> dictionary_en = {
  LabelsText.loginTittle: 'Welcome',
  LabelsText.loginPassword : 'Password',
  LabelsText.loginText:   'Log In',
  LabelsText.loginButtonOnline: 'Log In Inline',
  LabelsText.loginForget:  'Forget',
  LabelsText.loginRememberMe: 'Remember my Credentials',
  LabelsText.loginErrorAuth: 'Error Authentication',
  LabelsText.loginErrorEmailOrPass: 'Error Email or Password incorrect.',
  LabelsText.loginErrorEmailInvalid: 'Email Format invalid',
  LabelsText.homePageTittle: 'Welcome',
  LabelsText.homePageClient:  'Clients',
  LabelsText.homePageInsurance: 'Insurances',
  LabelsText.homePageSinister: 'Sinisters',
  LabelsText.clientTittle: 'Clients',
  LabelsText.clientNewRegister: 'You add a new client.',
  LabelsText.clientNew: 'Add a new Client.',
  LabelsText.clientName: 'Name',
  LabelsText.clientCodPostal: 'Postal Code',
  LabelsText.clientCity: 'City',
  LabelsText.clientTel: 'Tel',
  LabelsText.clientObservation: 'Observation',
  LabelsText.clientPass: 'Password',
  LabelsText.clientDeleteRegister: 'Client deleted.',
  LabelsText.clientNameVia: 'Via Name',
  LabelsText.clientNumberVia: 'Via Number',
  LabelsText.clientEmail: 'Email',
  LabelsText.clientLastName1: 'First Last Name',
  LabelsText.clientLastName2 : 'Second Last Name',
  LabelsText.clientClassVia : 'Via Class',
  LabelsText.seguroClientDni: 'Client Dni',
  LabelsText.seguroDateFinish: 'Expiration Date',
  LabelsText.seguroDateInit:  'Contract Date',
  LabelsText.seguroNoPoliza:  'Policy Number',
  LabelsText.seguroRamo: 'Branch',
  LabelsText.seguroTitle: 'Insurances',
  LabelsText.seguroModificar: 'Modify Insurance',
  LabelsText.seguroConditions: 'Conditions',
  LabelsText.seguroObserv: 'Observations',
  LabelsText.seguroActualizado: 'Updated the Insurance',
  LabelsText.seguroActualizar: 'Update',
  LabelsText.sinisterTitle: 'Sinister',
  LabelsText.sinisterDeleted: 'Siniester Removed',
  LabelsText.sinisterCouses: 'Causes',
    LabelsText.sinisterDoYouWantDelete: 'Do you want to delete the sinister?',
  LabelsText.sinisterDate: 'Date',
  LabelsText.sinisterImmission: 'Immission',
  LabelsText.sinisterNumber: 'Number',
  LabelsText.information: 'Information',
  LabelsText.formValidation: 'Need to validate your form',
  LabelsText.formRegister: 'Registry',
  LabelsText.formBack: 'Back',
  LabelsText.formDelete: 'Delete',
  LabelsText.formCancel: 'Cancel',
  LabelsText.settingsTitle: 'Settings',
  LabelsText.settingsLanguage: 'Language',
  LabelsText.settingsTheme: 'Theme',
  LabelsText.sensorErrorNotAvalible: 'Indicates the device does not have hardware support for biometrics.' ,
  LabelsText.sensorErrortPasscodeNotSet: 'Indicates that the user has not yet configured a passcode (iOS) or PIN/pattern/password (Android) on the device.',
  LabelsText.sensorErrorNotEnrolled: 'Indicates the user has not enrolled any biometrics on the device.',
  LabelsText.sensorErrorLockedOut: 'Indicates the API is temporarily locked out due to too many attempts.',
  LabelsText.sensorErrorOtherOperatingSystem: 'Indicates the device operating system is unsupported',
  LabelsText.sensorErrorPermanentlyLockedOut: ' Indicates the API is locked out more persistently than [lockedOut]. Strong authentication like PIN/Pattern/Password is required to unlock.Indicates the API is temporarily locked out due to too many attempts.',
  
  

};