

import 'package:test/util/app_strings.dart';

const Map<LabelsText, String> dictionary_es = {
  LabelsText.loginTittle: 'Bienvenido',
  LabelsText.loginPassword : 'Contraseña',
  LabelsText.loginText:   'Ingresar',
  LabelsText.loginButtonOnline: 'Ingresar con conexión',
  LabelsText.loginForget:  'Olvidar ',
  LabelsText.loginRememberMe: 'Recordar mis credenciales',
  LabelsText.loginErrorAuth: 'Error Authenticacion',
  LabelsText.loginErrorEmailOrPass: 'Correo o Contraseña erronea.',
  LabelsText.loginErrorEmailInvalid: 'Correo con formato invalido.',
  LabelsText.homePageTittle: 'Bienvenido',
  LabelsText.homePageClient:  'Clientes',
  LabelsText.homePageInsurance: 'Seguros',
  LabelsText.homePageSinister: 'Siniestros',
  LabelsText.clientTittle: 'Clientes',
  LabelsText.clientNewRegister: 'Nuevo cliente registrado.',
  LabelsText.clientNew: 'Agregar nuevo Cliente.',
  LabelsText.clientName: 'Nombre',
  LabelsText.clientCodPostal: 'Codigo Postal',
  LabelsText.clientCity: 'Ciudad',
  LabelsText.clientTel: 'Telefono',
  LabelsText.clientObservation: 'Observaciones',
  LabelsText.clientPass: 'Contraseña',
  LabelsText.clientDeleteRegister: 'Se ha eliminado un cliente.',
  LabelsText.clientNameVia: 'Nombre Via',
  LabelsText.clientNumberVia: 'Numero Via',
  LabelsText.clientEmail: 'Correo',
  LabelsText.clientLastName1: 'Apellido 1',
  LabelsText.clientLastName2 : 'Apellido 2',
  LabelsText.clientClassVia : 'Clase Via',
  LabelsText.seguroClientDni: 'Dni Cliente',
  LabelsText.seguroDateFinish: 'Fecha Final',
  LabelsText.seguroDateInit:  'Fecha Inicio',
  LabelsText.seguroNoPoliza:  'Numero Poliza',
  LabelsText.seguroRamo: 'Ramo',
  LabelsText.seguroModificar: 'Modificar Seguro',
  LabelsText.seguroTitle: 'Seguros',
  LabelsText.seguroConditions: 'Condiciones',
  LabelsText.seguroObserv: 'Observaciones',
  LabelsText.seguroActualizado: 'Seguro Actualizado',
  LabelsText.seguroActualizar: 'Actualizar',
  LabelsText.sinisterTitle: 'Siniestros',
  LabelsText.sinisterDeleted: 'Siniestro Eliminado',
  LabelsText.sinisterCouses: 'Causas',
  LabelsText.sinisterDoYouWantDelete: '¿Desea eliminar el siniestro?',
  LabelsText.sinisterDate: 'Fecha',
  LabelsText.sinisterImmission: 'Emision',
  LabelsText.sinisterNumber: 'Numero',
  LabelsText.information: 'Información',
  LabelsText.formValidation: 'Validar Formulario',
  LabelsText.formRegister: 'Registrar',
  LabelsText.formBack: 'Salir',
  LabelsText.formDelete: 'Eliminar',
  LabelsText.formCancel: 'Cancelar',
  LabelsText.settingsTitle: 'Configuraciones',
  LabelsText.settingsLanguage: 'Lenguaje',
  LabelsText.settingsTheme: 'Tema',
  LabelsText.sensorErrorNotAvalible: 'No tiene registrado ningun metodo biometrico' ,
  LabelsText.sensorErrortPasscodeNotSet: 'Aun no configura un passcode en (iOS) o PIN/pattern/password (Android) en el dispositivo.',
  LabelsText.sensorErrorNotEnrolled: 'No tiene almacenada ninguna huella dactilar',
  LabelsText.sensorErrorLockedOut: 'A agotado sus 5 intentos ahora tiene que esperar almenos 30 segundos para volver a intentar',
  LabelsText.sensorErrorOtherOperatingSystem: 'Su sitema operativo no es soportado',
  LabelsText.sensorErrorPermanentlyLockedOut: 'El sensor se ha bloqueado por muchos intentos fallidos se requiere una verificacion mas estricta con PIN/Pattern/Password',
  

};